# Learn more about services, parameters and containers at# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    login_complete:
        class: AppBundle\EventListener\LoginCompleted
        arguments: ['@security.token_storage', '@authentication_service']
        tags:
            - { name: kernel.event_subscriber }

    checkexp:
        class: AppBundle\EventListener\CheckExpAndInfoBeforeController
        arguments: ['@session', '@doctrine.orm.entity_manager', '@security.token_storage',
                    '@app.user.experience', '@authentication_service', '@game.pokemon.helper',
                    '@router'
                    ]
        tags:
            - { name: kernel.event_subscriber }

    authentication_service:
        public: true
        class: AppBundle\Utils\AuthenticationService
        arguments: ['@session', '@doctrine.orm.entity_manager', '@security.token_storage',
                    '@app.user.experience', '@game.pokemon.helper'
                    ]

    #app.file.twig.extension:
    #    class: AppBundle\Twig\Extension\FileExtension
    #    tags:
    #        - { name: twig.extension }

    #app.pokemon.twig.extension:
    #    class: AppBundle\Twig\Extension\PokemonInfoExtension
    #   arguments: ['@game.pokemon.helper']
    #    tags:
    #        - { name: twig.extension }

    #app.time.twig.extension:
    #    class: AppBundle\Twig\Extension\TimeExtension
    #    tags:
    #        - { name: twig.extension }

    app.left.table:
        public: true
        class: AppBundle\Utils\LeftTable
        arguments: ['@session']

    game.index:
        public: true
        class: AppBundle\Utils\GameIndex
        arguments: ['@doctrine.orm.entity_manager']

    game.pokemon.helper:
        public: false
        class: AppBundle\Utils\PokemonHelper

    game.attack.helper:
        class: AppBundle\Utils\AttackHelper

    app.user.experience:
        public: true
        class: AppBundle\Utils\UserExperience

    game.friends:
        public: true
        class: AppBundle\Utils\Friends
        arguments: [ '@doctrine.orm.entity_manager', '@session']

    game.reports:
        public: true
        class: AppBundle\Utils\Reports
        arguments: [ '@doctrine.orm.entity_manager']

    game.messages:
        public: true
        class: AppBundle\Utils\Messages
        arguments: [ '@doctrine.orm.entity_manager']

    game.collection:
        public: true
        class: AppBundle\Utils\Collection
        arguments: [ '@doctrine.orm.entity_manager', '@game.pokemon.helper', '@session']

    game.lottery:
        public: true
        class: AppBundle\Utils\Lottery
        arguments: [ '@doctrine.orm.entity_manager', '@session']

    game.settings:
        public: true
        class: AppBundle\Utils\GameSettings
        arguments: ['@doctrine.orm.entity_manager', '@session', '@security.password_encoder', '@request_stack']

    game.pokemon:
        public: true
        class: AppBundle\Utils\GamePokemon
        arguments: ['@doctrine.orm.entity_manager', '@game.pokemon.helper']

    game.pack:
        public: true
        class: AppBundle\Utils\GamePack
        arguments: ['@doctrine.orm.entity_manager', '@session', '@request_stack',
                    '@authentication_service', '@game.pokemon.helper', '@game.collection'
                    ]

    game.hospital:
        public: true
        class: AppBundle\Utils\GameHospital
        arguments: ['@doctrine.orm.entity_manager', '@session']

    game.training:
        public: true
        class: AppBundle\Utils\GameTraining
        arguments: ['@doctrine.orm.entity_manager', '@session']

    game.hunting.trainer.helper:
        public: true
        class: AppBundle\Utils\GameHuntingTrainerHelper
        arguments: ['@doctrine.orm.entity_manager', '@session', '@game.pokemon.helper', '@game.hunting.battle.pokemons']

    game.hunting:
        public: true
        class: AppBundle\Utils\GameHunting
        arguments: ['@doctrine.orm.entity_manager', '@session', '@game.collection',
                    '@game.pokemon.helper', '@game.hunting.helper', '@request_stack',
                    '@game.hunting.trainer.helper'
                    ]

    game.hunting.helper:
        class: AppBundle\Utils\GameHuntingHelper
        arguments: ['@game.pokemon.helper']

    game.shop:
        public: true
        class: AppBundle\Utils\GameShop
        arguments: ['@doctrine.orm.entity_manager', '@session']

    game.merchant:
        public: true
        class: AppBundle\Utils\GameMerchant
        arguments: ['@doctrine.orm.entity_manager', '@session']

    game.pokemons:
        public: true
        class: AppBundle\Utils\GamePokemons
        arguments: ['@doctrine.orm.entity_manager', '@session', '@authentication_service']

    game.hunting.battle.pokemons:
        public: true
        class: AppBundle\Utils\GameHuntingBattleBetweenPokemons
        arguments: ['@doctrine.orm.entity_manager', '@session', '@game.battle', '@authentication_service']

    game.hunting.catch:
        public: true
        class: AppBundle\Utils\GameHuntingCatch
        arguments: ['@doctrine.orm.entity_manager', '@session', '@game.shop', '@game.collection']

    game.profile.helper:
        public: true
        class: AppBundle\Utils\ProfileHelper

    game.profile:
        public: true
        class: AppBundle\Utils\GameProfile
        arguments: ['@doctrine.orm.entity_manager', '@session', '@game.profile.helper']

    game.market:
        public: true
        class: AppBundle\Utils\GameMarket
        arguments: ['@doctrine.orm.entity_manager', '@session', '@game.pack','@request_stack']

    game.battle:
        class: AppBundle\Utils\GameBattle
        arguments: ['@game.attack.helper']

    game.pokemon.change:
        public: true
        class: AppBundle\Utils\GamePokemonChange
        arguments: ['@doctrine.orm.entity_manager', '@session', '@authentication_service']

    game.exchange:
        public: true
        class: AppBundle\Utils\GameExchange
        arguments: ['@doctrine.orm.entity_manager', '@session', '@game.pokemon.helper']

    game.pokemons.exchange:
        public: true
        class: AppBundle\Utils\GamePokemonsExchange
        arguments: ['@doctrine.orm.entity_manager', '@session', '@game.pokemon.helper',
                    '@game.pack', '@game.pokemons', '@game.collection'
                    ]

    game.achievements.helper:
        public: false
        class: AppBundle\Utils\AchievementsHelper

    game.achievements:
        public: true
        class: AppBundle\Utils\GameAchievements
        arguments: ['@doctrine.orm.entity_manager', '@session', '@game.achievements.helper']

    game.training.pokemons:
        public: true
        class: AppBundle\Utils\GameTrainingPokemon
        arguments: ['@doctrine.orm.entity_manager', '@session']

    game.bugs:
        public: true
        class: AppBundle\Utils\Bugs
        arguments: ['@doctrine.orm.entity_manager', '@session']

    game.announcement:
        public: true
        class: AppBundle\Utils\GameAnnouncement
        arguments: ['@doctrine.orm.entity_manager']

    game.travel:
        public: true
        class: AppBundle\Utils\GameTravel
        arguments: ['@doctrine.orm.entity_manager', '@session']